Update 10-matrices.yaml

diff --git a/.github/workflows/10-matrices.yaml b/.github/workflows/10-matrices.yaml
--- a/.github/workflows/10-matrices.yaml
+++ b/.github/workflows/10-matrices.yaml
@@ -7,11 +7,17 @@ jobs:
   backwards-compatibility:
     runs-on: ${{ matrix.os }}
     strategy:
+      fail-fast: false
       matrix:
-        node-version: [16.x, 18.x, 21.x]
+        node-version: [18.x, 20.x, 21.x]
         os:
           - ubuntu-latest
           - windows-latest
+      
+        include:
+         - os: ubuntu-latest
+           node-version:  16.x
+           tag: experimental
 
     name: ${{ matrix.os }}-Node${{ matrix.node-version }}
 
@@ -21,6 +27,14 @@ jobs:
         with:
           node-version: ${{ matrix.node-version }}
 
+      - name: Fail if experimental
+        if: matrix.tag == 'experimental'
+        run: exit 1  # Fail if experimental tag is present
+
       - name: perform some tests
         run: |
          echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
+
+      - name: upload test results
+        run: |
+         echo "Uploading test results"
